### PR TITLE
Frontend uttam

### PR DESCRIPTION
**Pull request by uttamakwana**
I have done till Login Page and Sign Up page. And now I have to work on Card Page.

### CODE REVIEW

**Comment by MahiRavanKRG** [comment]
Hi there, We can discuss all the required changes here.
or whatever, we can talk here

**Review by MahiRavanKRG — APPROVED** [review]
I didn't sit and read all of it, and I wnent through all 28 files and review that this is a good initial project.

**Comment by uttamakwana** [comment]
Please accept my pull request

**Review by MahiRavanKRG — APPROVED** [review]
I will approve this pull request

**Pull request merged**
